### ISSUE TITLE
Binance historical data

### ISSUE THREAD

**Issue by goodboy** [pikers/piker#285]
Ties in with the work in #93 and #132.

Turns out they do offer approx 6 months worth of trades data:
- landing page: https://www.binance.com/en/landing/data
- download scripts: https://github.com/binance/binance-public-data/
  - cli docs: https://github.com/binance/binance-public-data/tree/master/python
  - [issue list](https://github.com/binance/binance-public-data/issues) shows some data discrepancies 
- example zipped `btcusdt` per month bundles: https://data.binance.vision/?prefix=data/spot/monthly/trades/BTCUSDT/
- equivalent api endpoint: https://binance-docs.github.io/apidocs/spot/en/#old-trade-lookup-market_data

---
#### TODO
- [ ] get trades data for all symbols into marketstore using a parallelized actor tree
- [ ] ensure aggregator works on `TICK` data as is supposed to be worked out in #93
- [ ] see if we can find historical L1?

**Comment by goodboy** [comment]
Oh, btw #305 adds the framing to get large OHLCV data sets loaded.

I think we should use that to help drive (historical) tick ingest.
