### ISSUE TITLE
Roll a `pikerized` `ib-gw` container, probably on `nixos`

### ISSUE THREAD

**Issue by goodboy** [pikers/piker#329]
Initial draft / POC was in #322 but more or less we need our own image likely built as:
- [`nixOS`](https://github.com/NixOS) so as to (mostly) avoid stupid dockerfile DSL syntax (in exchange for stupid `nixos` DSL syntax)
- way more minimal deps set then the original `ubuntu` image
- probably **not** `docker-compose` and just spin up the container via our `._ahab.py` super
- better image support for windows (see below)
- `sshd` for distributed deployments and `rsyscall` support
- use these `nixpkgs` for ib shite instead of installing from source as in the orig image: https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/office/ib

---
#### TODO: container config
- `ip rule add not unicast iif lo to 0.0.0.0/0 dport 4002` to filter public ip TCP connects at the OS layer (stateless firewall approach)
- [ ] figure out why the vnc auth still doesn't seem to be working?!?
- [ ] automated the equivalent docker-compose steps using our
  `.data._ahab` supervisor system
   - [ ] allow for API socket mapping to just be pulled direct from
  a user's `brokers.toml` and we'll just pass that direct to `IBC`'s
  config and do the same for any other embedded services (`sshd`, `ib-gw`, `x11vnc`, etc.)

---
#### TODO: windows support (maybe?)
For extra lolz, you can't use `--net=host` on windows as per:
- https://docs.docker.com/network/host/
   > The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.
   
So that means we'll need to:
- [ ] either go back to the `socat` stuff from the original container from waytrade
- [ ] use a `bridge` network inside the container namespace and do sensible routing table to map the necessary vnc and gw ports

**Comment by goodboy** [comment]
Further discussion with IBC peeps over in https://github.com/IbcAlpha/IBC/issues/67
