### ISSUE TITLE
tsdb multi-backend support and testing!

### ISSUE THREAD

**Issue by goodboy** [pikers/piker#485]
As per the slew of issues pertaining to time-series-db subsystems in piker seen here:
https://github.com/pikers/piker/labels/tsdb

---
#### Hi-level ToDo:
- [ ] breaking out the middle-ware history managment layer into it's own subpkg as per https://github.com/pikers/piker/issues/315
- [ ] trying out **at least one other** tsdb (probably `arctic`) and formalizing our OHLCV history apis as per the research options listed in #90
- [ ] actually documenting how to launch the db with `--tsdb` 😂 as per #313 
- [ ] generally speaking, much better management tools for manually pulling data from providers and populating a db instance either with cli or context-menu options in our charting app!
- [ ] real-time ingest of tick and signals (from our fsp layer) as per, for eg. #314
- [ ] a tick history to 1s OHLCV downsampler system that can be used cross-provider since most don't provide this low of a sample rate (think only one is `ib`?)

...

maybe more?

---
#### testing ToDo:
- [ ] db client connection, write, read and delete a time series loaded from either an offline sample or some provider we can always rely on (like `kraken` maybe?)
- [ ] basic tests for replication for those dbs which support it
