### ISSUE TITLE
Change `Position.clears` -> `.events`

### ISSUE THREAD

**Issue by goodboy** [pikers/piker#510]
As per related requirements in #345 and a bit of tasking in #489, it
probably makes sense to make this change for flexibility for things in
legacy markets like *splits*, *renames* and in modern (crypto) ones
things like *transfers*, *forks*, etc..

Of course the current schema records would just be flipped to `{'type':
'clear', ...}`.

There's a TODO in the respective `.accounting._pos` module:
- https://github.com/pikers/piker/pull/489/files#diff-5c46eaba5319d7f0646021c459f8284c4fe7815f0b87d471fa95671c81af0f0bR883

#### TODO:
- [ ] `type: ` initial field set schema
- [ ] removal of obsoleted top levels fields: eg. `split_ratio`
- [ ] add nice-to-have summary stats to the top level?
   - `bep` break even price
   - `duration` showing time span since last net-zero position?
   - `src_fiat` to allow defining which mkts the user chooses to project
     to particular "user fiat": the asset-money-tech of choice that the
     user wants to "price the position in terms of"
- [ ] add a top level `balances` table per account which shows the
  history of asset holdings per every single clear and transfer allowing
  for avoiding non-trading (non clearing) transactions to be filtered
  in position-pnl calcs?

---
Further adjustments to actual data schema and surrounding operating
machinery probably includes
- [ ] #496 final refinements and hopefully avoiding carrying our own
  fork!
  - after much [pain and anguish](https://github.com/pikers/piker/pull/336/commits/42db03c6888e6e550d6b38b268c63fcaac9e05ba) getting the `toml` encoder to output things sanely, i think it's just worth writing a super fast custom encoder that writes adhoc-ly in the format we want for `pps.toml`, the reader-writer separation is already what [`tomli` does (the fastest pure py reader soon to land in the stdlib)](https://github.com/hukkin/tomli-w) and and then we can just drop `toml` outright and worry about getting a general encoder later.
  - support better [indentation](https://github.com/toml-lang/toml#example) per broker-account for better readability, [indented tables](https://github.com/toml-lang/toml#example) per broker-account would be super nice if possible
   - <linktomlkitprhere>

- [x] finer grained file update update system
  - we added `.write_config()` to
    `.accounting._ledger.TransactionLedger` and the `PpTable` in #489

- offer a `ledgerd` / `accountantd` actor-service to take such file
  writing out-of-thread
  - [ ] we should add support for immediate config file (ledger or
    `pps.toml`) writing likely via the [`trio` async file IO
    apis](https://trio.readthedocs.io/en/stable/reference-io.html#asynchronous-filesystem-i-o)
    which use a bg thread to avoid main thread latency.

- [ ] ledger -> positions accounting offline audit subsys?
  -  will take in a backend generated ledger file(s) and check it
     against the current `pps.toml` state, complaining if there's
     a mismatch (depending on user settings and whether it's a paper
     account)
  - interop this with the new (proto-ed in #489) `piker ledger sync` CLI
    - will allow for easy import of positions wen moving between brokers
    - encourages backing all pps with ledger data

- [ ] high-level multi-account `PpTable` api that would avoid all the
  exit stacks as is currently implemented in the
  `ib.broker.trades_dialogue()` backend.

- [ ] Avoid `Position.size` being a state var and instead always
  computed from an
  `[e for e in Position.events if e['type'] in {'clear', 'transfer'}]`
  using `.calc_size()`
