### ISSUE TITLE
Move to `typer` for all clis

### ISSUE THREAD

**Issue by goodboy** [pikers/piker#513]
After building a prototype `ledger` syncing CLI in #489 (with follow up
coming in #512) I'm mega sold on going all in on `typer`:

- much terser definitions
- way prettier built-in output options via `rich` B)
- absolutely fantastic traceback styling

---
#### Todo porting:
- [ ] add as `typer[full]` dep
- [ ] port all existing cli modules:
  - [ ] root including `piker` group
  - [ ] `.data`
  - [ ] `.brokers`
  - [ ] `.ui`
  - [ ] any rando module scripts,
    - [ ] `.brokers.ib._flex_reports`
    - [ ] `snippets/qt_screen_info.py` (should prolly rename to
          `scripts/?`)

---
#### Todo new features:
- [ ] dump static watchlists using `rich.Table`
- [ ] try out using the live-update for real-time update on console?
  - https://rich.readthedocs.io/en/stable/live.html
  - would more or less be a replacement for the old `kivy` watchlist
    stuff that we were thinking of doing in `Qt` but i think a console
    version would be even *hipper* :joy:
